name: Datetime Parser Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8 mypy
        pip install -r requirements.txt
    - name: Static analysis with mypy
      run: |
        python -m mypy --ignore-missing-imports src
    - name: Static analysis with flake8
        run: |
          python -m flake8 --max-line-length=120 --per-file-ignores='patterns.py:E501' src
    - name: Test with pytest
      run: |
        pytest